### ISSUE TITLE
the installation instruction for ubuntu isn't working anymore

### ISSUE THREAD

**Issue by williaumwu** [aquasecurity/trivy-repo#1]
Hi,

I'm building a docker container with trivy installed.  It suddenly stopped working.  It was working before.  I didn't change anything, but something downstream changed.  It might have to do with the source for trivy?  I have double check things and don't know how to fix it.  Here are the steps and error I'm seeing.

OS: Ubuntu 16.04
Steps:

apt-get update
apt-get install wget apt-transport-https gnupg lsb-release apt-transport-https ca-certificates -y
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list
apt-get update
apt-get install trivy -y

Error:

Step 9/11 : RUN wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add - &&     echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list
 ---> Using cache
 ---> 1d45c11ca547
Step 10/11 : RUN apt-get install trivy -y
 ---> Running in fdba38996a64
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package trivy
The command '/bin/sh -c apt-get install trivy -y' returned a non-zero code: 100

**Comment by adel-s** [comment]
Any update on this? I have the same on Debian 9 (stretch).

**Comment by knqyf263** [comment]
@williaumwu @adel-s I'm sorry to be too late. I didn't notice this issue at all because an issue is usually opened in the trivy repo. It should work now.

**Comment by yed30** [comment]
Hello,
my pipelines failed since yesterday (this was working for months) with the following message:
**Unable to locate package trivy**

with the following code:
```
#### Add trivy repo & install trivy
RUN wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key |  apt-key add -
RUN echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main |  tee -a /etc/apt/sources.list.d/trivy.list
RUN apt-get update && apt-get install -y  trivy
```
