### ISSUE TITLE
deploy job timeout

### ISSUE THREAD

**Issue by mbrndtgn** [aquasecurity/trivy-repo#21]
The deploy job fails regularly with `Error: Timeout reached, aborting!`. For example here: https://github.com/aquasecurity/trivy-repo/actions/runs/3846320467/jobs/6551880244#step:2:138

I'm not familiar with the GitHub Actions limits and what the defaults are, but it seems like the deploy job gets canceled after 10min which prevents updates getting pushed to the repos.

**Comment by knqyf263** [comment]
@afdesk is trying to improve it.

**Comment by afdesk** [comment]
@mbrndtgn thanks for the report! 
yes,yes. It's a known issue and i'm trying to fix right now.
